-- Cart Table Start

create table
    public."Cart" (
                      id bigint generated by default as identity,
                      created_at timestamp with time zone not null default now(),
                      sku character varying not null,
                      name character varying not null,
                      quantity int not null,
                      unit_price real not null,
                      total_price real null,
                      user_id character varying null,
                      product_id int not null,
                      constraint Cart_pkey primary key (id),
                      constraint Cart_id_key unique (id)
) tablespace pg_default;

-- Cart Table End

-- Pricing Table Start

create table
    public."PricingRule" (
                             id bigint generated by default as identity,
                             created_at timestamp with time zone not null default now(),
                             sku character varying not null,
                             rule_type character varying not null,
                             rule_details character varying null,
                             price_detail real null,
                             constraint PricingRules_pkey primary key (id),
                             constraint PricingRules_id_key unique (id)
) tablespace pg_default;

-- Pricing Table End

-- Product Table Start

create table
    public."Product" (
                         id bigint generated by default as identity,
                         created_at timestamp with time zone not null default now(),
                         sku character varying not null,
                         name character varying not null,
                         price real not null,
                         quantity int not null,
                         constraint Product_pkey primary key (id),
                         constraint Product_id_key unique (id)
) tablespace pg_default;

-- Product Table End